spring:
  mail:
    host: smtp.gmail.com
    username: won9497@gmail.com
    port: 587
    password: vdrzeawshrvzqkmy
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
