spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/loobie
    username: sa
    password:
    driver-class-name: org.h2.Driver
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  profiles:
    include: aws, oauth
    active: local
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-h2.sql
#  test OAuth
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: test
#            client-secret: test
#            scope: profile_nickname, profile_image, account_email

logging:
  level:
    org.hibernate.SQL: debug
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

aws:
  s3:
    bucket: s3-loobie